#### Задание1

In [2]:
import numpy as np

In [3]:
a = np.array

In [4]:
a = ([1, 2, 3, 3, 1], [6, 8, 11, 10, 7])

In [5]:
print(a)

([1, 2, 3, 3, 1], [6, 8, 11, 10, 7])


In [6]:
a = np.transpose(a)

In [7]:
print(a)

[[ 1  6]
 [ 2  8]
 [ 3 11]
 [ 3 10]
 [ 1  7]]


In [8]:
mean_a = np.zeros(2,)

In [9]:
np.mean(a, axis=0, out = mean_a)

array([2. , 8.4])

#### Задание2

In [10]:
a_centered = np.zeros(2,)
a_centered = a - mean_a

In [11]:
print(a_centered)

[[-1.  -2.4]
 [ 0.  -0.4]
 [ 1.   2.6]
 [ 1.   1.6]
 [-1.  -1.4]]


#### Задание3

In [12]:
a_centered_sp = np.zeros(2,)

In [13]:
a_centered_sp = np.inner(a_centered[0:, 0], a_centered[0:, 1])

In [14]:
print(a_centered_sp)

8.0


In [15]:
print(a_centered[0:, 1])
print(a_centered[0:, 0])

[-2.4 -0.4  2.6  1.6 -1.4]
[-1.  0.  1.  1. -1.]


In [16]:
N = a_centered.shape[0]

In [17]:
print(a_centered_sp/(N-1))

2.0


#### Задание4

In [23]:
print(np.cov(a, rowvar = False)) #Офигенная формула. Все предыдущие страдания одной строкой.

[[1.  2. ]
 [2.  4.3]]
